
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Flow = 0.28F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Pressure with predicted Pressure from sample data...\n\n");


Console.WriteLine($"Pressure: {20F}");
Console.WriteLine($"Flow: {0.28F}");


var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Pressure: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

